language: node_js
node_js:
  - "12"
services:
  - docker
branches:
 only:
   - master

before_install:
  - npm install

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t 18201430329/umiprojects:latest .
  - docker push 18201430329/umiprojects:latest